export default {
  ignores: [
    // Build output is generated and should not be linted.
    'dist/**',
    // Dependencies are third-party code.
    'node_modules/**',
    // Coverage reports are generated by Vitest/Istanbul.
    'coverage/**',
    // Runtime log files are generated output.
    'logs/**',
    // TypeScript incremental metadata is generated by the compiler.
    '*.tsbuildinfo',
    // JavaScript test helpers are outside the typed TypeScript lint scope.
    'test/**/*.js',
    // Vitest config is excluded from typed source linting.
    'vitest.config.mts',
    // Root-level spec files are excluded from production typed linting.
    '*.spec.ts',
    // JavaScript config/runtime files are outside this TypeScript lint target
    // (the flat config modules themselves, lint-staged/commitlint, etc.).
    '**/*.{js,mjs,cjs}',
  ],
};
